services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - qdrant
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/rag_ros2
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - CLEARML_WEB_HOST=http://clearml:8080
      - CLEARML_API_HOST=http://clearml:8008
      - CLEARML_FILES_HOST=http://clearml:8081

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  clearml:
    image: allegroai/clearml:latest
    ports:
      - "8080:8080"
      - "8008:8008"
      - "8081:8081"
    volumes:
      - clearml_data:/opt/clearml

volumes:
  mongodb_data:
  qdrant_data:
  clearml_data: