version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"

  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    platform: linux/amd64
    environment:
      CLEARML_AGENT_GIT_USER: "mannadamay12"
      CLEARML_AGENT_GIT_PASS: "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"
    ports:
      - "8080:8080"

volumes:
  mongo-data:
