sources:
  documentation:
    ros2:
      base_url: "https://docs.ros.org/en/jazzy/"
      sections:
        - "Installation.html"
        - "Tutorials.html"
        - "How-To-Guides.html"
        - "Concepts.html"
      version: "jazzy"
    nav2:
      base_url: "https://docs.nav2.org/"
      sections:
        - "getting_started/index.html"
        - "development_guides/index.html"
        - "concepts/index.html"
        - "setup_guides/index.html"
        - "tutorials/index.html"
        - "plugin_tutorials/index.html"
        - "configuration/index.html"
        - "tuning/index.html"
        - "behavior_trees/index.html"
        - "commander_api/index.html"
      version: "latest"
    moveit2:
      base_url: "https://moveit.picknik.ai/main/doc"
      sections:
        - "tutorials/tutorials.html"
        - "examples/examples.html"
        - "concepts/concepts.html"
        - "how_to_guides/how_to_guides.html"
      version: "main"
    gazebo:
      base_url: "https://gazebosim.org/docs/latest"
      sections:
        - "getstarted"
        - "tutorials"
        - "ros_installation"
        - "architecture"
      version: "latest"
  
  github_repos:
    ros2:
      - name: "ros2/ros2"
        url: "https://github.com/ros2/ros2"
        branches: ["humble", "foxy"]  # LTS releases
      - name: "ros2/examples"
        url: "https://github.com/ros2/examples"
        branches: ["humble", "foxy"]
      - name: "ros2/documentation"
        url: "https://github.com/ros2/documentation"
        branches: ["humble", "foxy"]
  
  youtube_playlists:
    ros2:
      - channel_id: "UCK8Y_nwY_L1DaHXrZUUozAg"  # ROS2 Official
        playlists: 
          - "PLNw1_R4SfJQf_i5un9AGGj1jmqWJ4yE4i"  # ROS2 Tutorials Playlist
          - "PLNw1_R4SfJQfQUVT6TJAXcv2yIQjzNHXz"  # ROS2 Demos
      - channel_id: "UCt6Lag-vv25fSpX_yf2Rs1Q"  # The Construct
        playlists:
          - "PLK0b4e05LnzZpAM3NxXXUUNfbqC2YLIGq"  # ROS2 Basics Course